#!/usr/bin/env bash
# =============================================================================
#  start.sh — Cloud startup script for YouTube Downloader API
#  Works on Render, Railway, and any Linux-based cloud host.
#
#  Environment variables (set in the cloud platform's dashboard):
#
#    YDA_COOKIES_CONTENT   Base64-encoded contents of a Netscape cookies.txt
#                          file exported from a real YouTube browser session.
#                          If set, it will be decoded and written to cookies.txt
#                          before the server starts.
#
#    YDA_CONFIG_CONTENT    Base64-encoded contents of a custom config.yml.
#                          If set, it overrides the default config.yml.
#                          (Optional — the bundled config.yml is production-ready.)
#
#    YDA_CONFIG_FILE_PATH  Absolute/relative path to the config YAML to use.
#                          Defaults to config.yml in the project root.
#
#    PORT                  Port to bind the server on.
#                          Automatically set by Render and Railway.
#                          Defaults to 8000 if not set.
#
# =============================================================================

set -euo pipefail

echo "🚀  Starting YouTube Downloader API..."

# ---------------------------------------------------------------------------
# 1. Write cookies.txt from base64 env var (if provided), or create a valid
#    empty Netscape cookies file so the app's cookiefile validator passes.
# ---------------------------------------------------------------------------
if [ -n "${YDA_COOKIES_CONTENT:-}" ]; then
    echo "🍪  Decoding YDA_COOKIES_CONTENT → cookies.txt"
    echo "$YDA_COOKIES_CONTENT" | base64 -d > cookies.txt
    echo "    ✓ cookies.txt written ($(wc -l < cookies.txt) lines)"
else
    echo "⚠️   YDA_COOKIES_CONTENT not set."
    echo "    Creating an empty cookies.txt so the app can start."
    echo "    ⚡ YouTube may block requests from cloud IPs without real cookies."
    echo "    Set YDA_COOKIES_CONTENT to a base64-encoded Netscape cookies.txt for reliability."
    # Write a valid but empty Netscape cookies file header
    printf '# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n# This file was generated by start.sh (no cookies provided).\n' > cookies.txt
fi


# ---------------------------------------------------------------------------
# 2. Write custom config.yml from base64 env var (if provided)
# ---------------------------------------------------------------------------
if [ -n "${YDA_CONFIG_CONTENT:-}" ]; then
    echo "⚙️   Decoding YDA_CONFIG_CONTENT → custom_config.yml"
    echo "$YDA_CONFIG_CONTENT" | base64 -d > custom_config.yml
    export YDA_CONFIG_FILE_PATH="custom_config.yml"
    echo "    ✓ custom_config.yml written, YDA_CONFIG_FILE_PATH set."
fi

# ---------------------------------------------------------------------------
# 3. Ensure static working directory exists
# ---------------------------------------------------------------------------
mkdir -p static/downloads static/temps
echo "📁  Working directories ready: static/"

# ---------------------------------------------------------------------------
# 4. Determine port
# ---------------------------------------------------------------------------
PORT="${PORT:-8000}"
echo "🌐  Binding on port $PORT"

# ---------------------------------------------------------------------------
# 5. Launch the server
#    uv run ensures the correct venv / Python version is used.
#    fastapi run binds to 0.0.0.0 by default.
# ---------------------------------------------------------------------------
echo "✅  Launching FastAPI server..."
exec uv run python -m fastapi run app --host 0.0.0.0 --port "$PORT"
