#!/usr/bin/env bash
# =============================================================================
#  start.sh — Cloud startup script for YouTube Downloader API
#  Works on Render, Railway, and any Linux-based cloud host.
#
#  Environment variables (set in the cloud platform's dashboard):
#
#    YDA_COOKIES_CONTENT   Base64-encoded contents of a Netscape cookies.txt
#                          file exported from a real YouTube browser session.
#                          If set, it will be decoded and written to cookies.txt
#                          before the server starts.
#
#    YDA_CONFIG_CONTENT    Base64-encoded contents of a custom config.yml.
#                          If set, it overrides the default config.yml.
#                          (Optional — the bundled config.yml is production-ready.)
#
#    YDA_CONFIG_FILE_PATH  Absolute/relative path to the config YAML to use.
#                          Defaults to config.yml in the project root.
#
#    YDA_API_KEY           API key required by protected endpoints when
#                          require_api_key is enabled in config.
#
#    YDA_DATABASE_ENGINE   Database URL override, useful for managed Postgres.
#
#    PORT                  Port to bind the server on.
#                          Automatically set by Render and Railway.
#                          Defaults to 8000 if not set.
#
#  Also auto-detects a `deno` binary on PATH (installed via nixpacks.toml)
#  and wires its path into config.yml's js_runtime field, so yt-dlp can
#  solve YouTube's player challenges. No env var needed for this.
#
# =============================================================================

set -euo pipefail

echo "🚀  Starting YouTube Downloader API..."

# ---------------------------------------------------------------------------
# 1. Write cookies.txt from base64 env var (if provided), or create a valid
#    empty Netscape cookies file so the app's cookiefile validator passes.
# ---------------------------------------------------------------------------
if [ -n "${YDA_COOKIES_CONTENT:-}" ]; then
    echo "🍪  Decoding YDA_COOKIES_CONTENT → cookies.txt"
    echo "$YDA_COOKIES_CONTENT" | base64 -d > cookies.txt
    echo "    ✓ cookies.txt written ($(wc -l < cookies.txt) lines)"
else
    echo "⚠️   YDA_COOKIES_CONTENT not set."
    echo "    Creating an empty cookies.txt so the app can start."
    echo "    ⚡ YouTube may block requests from cloud IPs without real cookies."
    echo "    Set YDA_COOKIES_CONTENT to a base64-encoded Netscape cookies.txt for reliability."
    # Write a valid but empty Netscape cookies file header
    printf '# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n# This file was generated by start.sh (no cookies provided).\n' > cookies.txt
fi


# ---------------------------------------------------------------------------
# 2. Write custom config.yml from base64 env var (if provided)
# ---------------------------------------------------------------------------
if [ -n "${YDA_CONFIG_CONTENT:-}" ]; then
    echo "⚙️   Decoding YDA_CONFIG_CONTENT → custom_config.yml"
    echo "$YDA_CONFIG_CONTENT" | base64 -d > custom_config.yml
    export YDA_CONFIG_FILE_PATH="custom_config.yml"
    echo "    ✓ custom_config.yml written, YDA_CONFIG_FILE_PATH set."
fi

# ---------------------------------------------------------------------------
# 3. Point config at the deno binary installed via nixpacks.toml, so yt-dlp
#    can solve YouTube's player challenges (avoids the "No supported
#    JavaScript runtime could be found" warning / missing formats).
# ---------------------------------------------------------------------------
ACTIVE_CONFIG_FILE="${YDA_CONFIG_FILE_PATH:-config.yml}"
DENO_PATH="$(command -v deno || true)"
if [ -n "$DENO_PATH" ]; then
    echo "🦕  Found deno at $DENO_PATH — wiring into $ACTIVE_CONFIG_FILE"
    # Replace an existing (possibly blank) js_runtime line, or append one.
    if grep -q '^js_runtime *:' "$ACTIVE_CONFIG_FILE"; then
        sed -i "s|^js_runtime *:.*|js_runtime : $DENO_PATH|" "$ACTIVE_CONFIG_FILE"
    else
        printf '\njs_runtime : %s\njs_runtime_name : deno\n' "$DENO_PATH" >> "$ACTIVE_CONFIG_FILE"
    fi
else
    echo "⚠️   deno not found on PATH — yt-dlp will run without a JS runtime."
    echo "    Add \"deno\" to nixPkgs in nixpacks.toml to enable it."
fi

# ---------------------------------------------------------------------------
# 4. Ensure static working directory exists
# ---------------------------------------------------------------------------
mkdir -p static/downloads static/temps
echo "📁  Working directories ready: static/"

# ---------------------------------------------------------------------------
# 5. Determine port
# ---------------------------------------------------------------------------
PORT="${PORT:-8000}"
echo "🌐  Binding on port $PORT"

# ---------------------------------------------------------------------------
# 6. Launch the server
#    uv run ensures the correct venv / Python version is used.
#    fastapi run binds to 0.0.0.0 by default.
# ---------------------------------------------------------------------------
echo "✅  Launching FastAPI server..."
exec uv run python -m fastapi run app --host 0.0.0.0 --port "$PORT"
